#################################################################
# Contains all secrets

# Secrets contain the sensitive information about secret
# configs such as passwords and auth data
# Make sure secret values are base64 encoded
# we will use azure-key-vault in future for sensitive information
##################################################################
---
apiVersion: v1
kind: Secret
metadata:
  name: be-users-dev
  release: dev
  namespace: vlogmakelaars-experimental
type: Opaque
data:
  mongo.user: YWRtaW4=
  mongo.password: YWRtaW4xMjM=
  keycloak.client_secret: YWVhNzFlMDYtOTViYS00ZjRkLTkyNTctMzVmY2FhODJlNzI0
---
